apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: sac-validation-webhook-config
webhooks:
  - name: sac-webhook.default.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      service:
        name: sac-webhook-service
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNQRENDQWVPZ0F3SUJBZ0lRYlZqQ3JvWUZMYi9zWjhrdFI2eVNzREFLQmdncWhrak9QUVFEQWpCSE1Sc3cKR1FZRFZRUUtFeEpIYjBzNGN5QlRaV04xY21sMGVTQk1ZV0l4S0RBbUJnTlZCQU1USDNOaFl5MTNaV0pvYjI5cgpMWE5sY25acFkyVXVaR1ZtWVhWc2RDNXpkbU13SGhjTk1qWXdNekF6TWpFek56SXlXaGNOTWpjd016QXpNakV6Ck56SXlXakJITVJzd0dRWURWUVFLRXhKSGIwczRjeUJUWldOMWNtbDBlU0JNWVdJeEtEQW1CZ05WQkFNVEgzTmgKWXkxM1pXSm9iMjlyTFhObGNuWnBZMlV1WkdWbVlYVnNkQzV6ZG1Nd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqTwpQUU1CQndOQ0FBUXNxNGxyNHNad3pib3RFQkh4R0ZTZittc210VENMRWFiQWViemNwMWZyTUcrMVBWdFdHVGFxCkZ3dHFZS2RCMmV3R250N0ZpdExYV2ViZnR5d1dCYnl0bzRHd01JR3RNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVQKQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUdwpFdGhIaGt6OUV6UitkeHdlc25BeURQRmZSREJXQmdOVkhSRUVUekJOZ2g5ellXTXRkMlZpYUc5dmF5MXpaWEoyCmFXTmxMbVJsWm1GMWJIUXVjM1pqZ2hOellXTXRkMlZpYUc5dmF5MXpaWEoyYVdObGdnbHNiMk5oYkdodmMzU0gKQkg4QUFBR0hCQUFBQUFBd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ0F2STFJazBkZmV2SlZvdFdGSFNGY0FwZAoxUktzUVU2Vmk1aWx1Tk45MjVjQ0lEMlF6Z1dZMjUxV0VEN21BSy9Uc1d1bmhBY09zSnFRcGIwTWlZcElGY0V3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]