apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: my-validation-webhook
webhooks:
  - name: validate.example.com
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    clientConfig:
      service:
        name: validation-webhook-service
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJzakNDQVZlZ0F3SUJBZ0lRR3lCU1RkSHl6enEvcG9oL0xuZStLakFLQmdncWhrak9QUVFEQWpBL01Sc3cKR1FZRFZRUUtFeEpIYjBzNGN5QlRaV04xY21sMGVTQk1ZV0l4SURBZUJnTlZCQU1URjNOaFl5MTNaV0pvYjI5cgpMbVJsWm1GMWJIUXVjM1pqTUI0WERUSTJNREl4TmpFNU5EWXpORm9YRFRJM01ESXhOakU1TkRZek5Gb3dQekViCk1Ca0dBMVVFQ2hNU1IyOUxPSE1nVTJWamRYSnBkSGtnVEdGaU1TQXdIZ1lEVlFRREV4ZHpZV010ZDJWaWFHOXYKYXk1a1pXWmhkV3gwTG5OMll6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGVEFGbjViL3dwYgpudFhyWXdRR1NDaWxub2prT0RRaFYwTEh0S0kvcnROaDRJSHNIcEJ0TENUT01KYk5OZG1aRm5VM2JzT0hxZWVHCjlYWmZIV2ZLdVNpak5UQXpNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0QKQVRBTUJnTlZIUk1CQWY4RUFqQUFNQW9HQ0NxR1NNNDlCQU1DQTBrQU1FWUNJUUN1QUtPSW45WHhFeEhJV2JYKwpPRWwrOE1IaWRUcnYvOFVjMHhNZzBnNVBnZ0loQUxpWEtISHgzUUpRNjdpSnBKL29Fbk1yNlJuU3hTcVF3d1B0ClJWdThTK0hxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
