---
apiVersion: v1
kind: Pod
metadata:
  name: good-pod
spec:
  containers:
    - name: good-container
      image: nginx:alpine
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-privileged
spec:
  containers:
    - name: bad-container
      image: alpine
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-without-labels
spec:
  containers:
    - name: test
      image: busybox
      command: ["echo", "test"]