apiVersion: v1
kind: Service
metadata:
  name: webhooklite-service
  namespace: default
spec:
  selector:
    app: webhooklite
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  type: ClusterIP