apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhooklite-validator
webhooks:
  - name: webhooklite.default.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["default"]  # Exclude the "default" namespace
    clientConfig:
      service:
        name: webhooklite-service
        namespace: default
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR5RENDQXJDZ0F3SUJBZ0lVWlFWcXhsMUZmelVvbHBNWktRUXVQMDlINXE4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZkMlZpYUc5dmEyeHBkR1V0YzJWeWRtbGpaUzVrWldaaGRXeDBMbk4yWXpBZQpGdzB5TmpBek1EVXhPRFUwTXpWYUZ3MHlOekF6TURVeE9EVTBNelZhTUNveEtEQW1CZ05WQkFNTUgzZGxZbWh2CmIydHNhWFJsTFhObGNuWnBZMlV1WkdWbVlYVnNkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDTi9uZXpZZmMzZ1dFQ2lVeDlseWxqOVhJUkg4dGRTQTJlVlRLK0FhSUxjL1VZTEhGaApXenFoV0tOMmI2K0Q1N1YvZExYcVVBL3g2dW1yUEsrVG5LaXdydmpIYTBwNlZWOHVSajZzV0NGYXRWeVpXaVNjClB1TGhaSUVwdFhjWkhucnFmcXhxMFIvRmkyNzBLckdSMnVzUzVmMkF5UlVPMEduZ2RiV3R5ZENyZ3NkZ3lwajEKdTljV2xiaVVCNzJMeCs1L1dqSnhCUzVXRjZ1bUU4Q0RLbUkzbDN2ZmdqOXhoY1owNGdPTUQ3OGUzSWhxUS9TegpaVHhBR0ExeGFmalVhbE5pUlhPM1hIN1paMjBRWVJOdTJXVVJ1MjBDWmNodHVNMnhiTnBJUHBEK1VjQkU3WnlyCmtVaFJhQ2VrQmlxbml5QndJVWd1OERCUC9ZUnZ1TEtQSHZIbEFnTUJBQUdqZ2VVd2dlSXdDd1lEVlIwUEJBUUQKQWdRd01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNSUdlQmdOVkhSRUVnWll3Z1pPQ0UzZGxZbWh2YjJ0cwphWFJsTFhObGNuWnBZMldDRzNkbFltaHZiMnRzYVhSbExYTmxjblpwWTJVdVpHVm1ZWFZzZElJZmQyVmlhRzl2CmEyeHBkR1V0YzJWeWRtbGpaUzVrWldaaGRXeDBMbk4yWTRJdGQyVmlhRzl2YTJ4cGRHVXRjMlZ5ZG1salpTNWsKWldaaGRXeDBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNnZ2xzYjJOaGJHaHZjM1NIQkg4QUFBRXdIUVlEVlIwTwpCQllFRklMNFlPUEIwYThXRlkwMTd4eGsxYmprMmhKeU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUFxTmNNCk9HbGVyRHRpdGhIcDhmelhFVVQzK3N4eTFpOE05aWczckRaaUpHSHFJdlY4a3VUdHYxN0tjR3o2Zkk4SXhWYSsKRFo3WURoQUV0SXhzY3VuRGplZkNuQVFwRmpMTDFidGlSdzBXaEFjclBmRmhuTTcyd1gyU2NGcUNBSC9KeHJCLwpRek9zRXR3YjFRM3JlRlpROHB4bFNLcUNlMzhqVVovcm9JaGg5RXpuQ08yUHJqWXllSUdUbHNQelFkYzU1bFdiCjY2aTNXbW9Ec2pSNEpLQkp3cVkwaCt6MjI2MlhVRmE1ZjNlLzFnQkRZaXRyZWdaSjd1N2NGM1RZM0hoSnMyQ0MKQnJBczJRQUgvZjZYY0x2Q0hCUkxDc1dKSDB6UkdPYmN2QjJlajdnaVIzdHBMbGRGK2NaQzRubkhoMTVDMHVnQgpxc1pBTkkzVjNhT1pvbXE2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]