apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-validator
webhooks:
  - name: webhook.webhook-system.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["webhook-system"]  # 👈 reject only our namespace
    clientConfig:
      service:
        name: webhook-service
        namespace: webhook-system
        path: /validate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVJVENDQXdtZ0F3SUJBZ0lVYzFKTlZQbFVEd2wvQjFMMUVjNVJqTGREenNzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xURXJNQ2tHQTFVRUF3d2lkMlZpYUc5dmF5MXpaWEoyYVdObExuZGxZbWh2YjJzdGMzbHpkR1Z0TG5OMgpZekFlRncweU5qQXpNVFl5TURVeU5UbGFGdzB5TnpBek1UWXlNRFV5TlRsYU1DMHhLekFwQmdOVkJBTU1JbmRsClltaHZiMnN0YzJWeWRtbGpaUzUzWldKb2IyOXJMWE41YzNSbGJTNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUN5NXBOMnowTWFXdElTS29peU4wQW1saDZ3TDFvbVE0elA2a2lRTVNvWgpsdVpGbUduU0tLVjFzTTNxZzhZTlRHQmtvbUtVWXlhWlFpSy9xdnJYcnRvUjY4NGZVLzNzYmhZVEQwZWpaVWNBCkw5N1pjckxnOU1oUnBzdnBJSS9wK0lMOW40SHJxa3NRdG4yckFmYjNWT3VqMXFXWG9tSXBDQkhoaGhheGFvM0oKZTlKK0ZyUGxqRWVkS1BRR1g3UENKNTB6ajhMRVdLZEVjSzFZWWFvK3A4Y1RqcTNCU3dQTnE2aVV1OVd3TzlFWQpyTFdDcTlGc2sreUx6MFJXY2ZNbkM0TFhLRHR3MFovblVvdTdob2hySFY4RkVhMUY2a2dtODFqOTJmRnFvbnJPCmViSkhVNmlTcE1FQ0g3SHhucVRRUWhXSERNcUJBaHVSMjU1Mk15OTBYVTBoQWdNQkFBR2pnZ0UzTUlJQk16QUwKQmdOVkhROEVCQU1DQkRBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdnZThHQTFVZEVRU0I1ekNCNUlJaQpkMlZpYUc5dmF5MXpaWEoyYVdObExuZGxZbWh2YjJzdGMzbHpkR1Z0TG5OMlk0SXhkMlZpYUc5dmF5MXpaWEoyCmFXTmxMbmRsWW1odmIyc3RjM2x6ZEdWdExuTjJZeTUzWldKb2IyOXJMWE41YzNSbGJZSTFkMlZpYUc5dmF5MXoKWlhKMmFXTmxMbmRsWW1odmIyc3RjM2x6ZEdWdExuTjJZeTUzWldKb2IyOXJMWE41YzNSbGJTNXpkbU9DUTNkbApZbWh2YjJzdGMyVnlkbWxqWlM1M1pXSm9iMjlyTFhONWMzUmxiUzV6ZG1NdWQyVmlhRzl2YXkxemVYTjBaVzB1CmMzWmpMbU5zZFhOMFpYSXViRzlqWVd5Q0NXeHZZMkZzYUc5emRJY0Vmd0FBQVRBZEJnTlZIUTRFRmdRVVhYTUUKNUdSUDNTR255ZFlwWVZ0bS9IUnVweGt3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhyaWNmU2JpanNXZk9FRwpzOUF0UGk3UHZvbWlRL3hHbkdRbVQ3dmJJZzJRSVkwTGxrNU5EQlAvdUMyaWZNaHpMbDM1N1lscG45YmV1UWFuCkx3NCt5VGNhUXpHQ3NzcmMrT1pubmszNEw0SXloaUM2OXlpenVDaXB4RmNMczVxeElLa1Nja004SHpETlIvT20KQjM5M3pneEZtajZtYkFkazl4czFZM0ljbzc4aU9VOENxUmhnMmNDaEVucFVWeGZET0Y0cVFLZWFIWlNOTlNHego2VGVRMU9DekhkYXErdnk5cGJ5RlZYRXBLR1RDeTl5OVJYN1RWR2tNL3libHJzeVcvWGgvY3BlMnNtWkQ2K2k3CnpMNnViYktCOHdOUWJnODduMWRQd3V4TkFNUzVGZkRqYllPWEh1dFM3bjBCYnVTNWF1MG1mdVVxbVBwdlVhVFEKWkxOQmNqTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=  # by the script
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
